Hotfix trt read requset
tagion/tagion pull request #399
Opened 2024-01-18 16:27 UTC by ivanbilan-i25s

2024-01-19 08:33 UTC, lucasnethaj commented on src/lib-services/tagion/services/TRTService.d
> +                Document response = hirpc.result(receiver, params).toDoc;
Can we use Document.init instead of allocating and empty HiBON

2024-01-19 14:06 UTC, imrying commented on src/lib-services/tagion/services/TRTService.d
> +                Document response = hirpc.result(receiver, params).toDoc;
I guess it is the same or what?

2024-01-19 14:59 UTC, lucasnethaj commented on src/lib-services/tagion/services/TRTService.d
> +                Document response = hirpc.result(receiver, params).toDoc;
I should be the same, the empty HiBON just gets constructed to a Document in the hirpc function.
I'm not sure what is the difference between Document.init and Document()

2024-01-19 15:09 UTC, lucasnethaj requested changes

2024-01-19 15:09 UTC, lucasnethaj commented on src/lib-services/tagion/services/TRTService.d
> +                const sender = hirpc.Sender(null, message);
It would be better if you could use the hirpc.error()/hirpc.result() function instead of the Sender constructor directly

2024-01-20 13:56 UTC, imrying approved these changes

2024-01-20 13:56 UTC, lucasnethaj approved these changes

2024-01-20 13:57 UTC, lucasnethaj approved these changes
We'll make the requested changes in master

2024-01-20 13:58 UTC, merged